/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconArcticonsCircle: typeof import('~icons/arcticons/circle')['default']
    IconArcticonsHamburgerMenu: typeof import('~icons/arcticons/hamburger-menu')['default']
    IconArcticonsHamburgerMenuc: typeof import('~icons/arcticons/hamburger-menuc')['default']
    IconArcticonsMultiAppUninstaller: typeof import('~icons/arcticons/multi-app-uninstaller')['default']
    IconArcticonsNoxcleaner: typeof import('~icons/arcticons/noxcleaner')['default']
    IconArcticonsRectangleHorizontal: typeof import('~icons/arcticons/rectangle-horizontal')['default']
    IconArcticonsSquare: typeof import('~icons/arcticons/square')['default']
    IconArcticonsWearInstaller: typeof import('~icons/arcticons/wear-installer')['default']
    IconIconParkRectangleOne: typeof import('~icons/icon/park-rectangle-one')['default']
    IconLineMdCircle: typeof import('~icons/line/md-circle')['default']
    IconLineMdSquare: typeof import('~icons/line/md-square')['default']
    IconMdiCircleOutline: typeof import('~icons/mdi/circle-outline')['default']
    IconMdiRectangle: typeof import('~icons/mdi/rectangle')['default']
    IconMdiRectangleOutline: typeof import('~icons/mdi/rectangle-outline')['default']
    IconMdiSquareOutline: typeof import('~icons/mdi/square-outline')['default']
    IconTdesignCircle: typeof import('~icons/tdesign/circle')['default']
    IconTdesignClearFormatting1: typeof import('~icons/tdesign/clear-formatting1')['default']
    IconTdesignInstall: typeof import('~icons/tdesign/install')['default']
    IconTdesignRectangle: typeof import('~icons/tdesign/rectangle')['default']
    IconTdesignUninstall: typeof import('~icons/tdesign/uninstall')['default']
  }
}
