/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconArcticonsCircle: typeof import('~icons/arcticons/circle')['default']
    IconArcticonsHamburgerMenu: typeof import('~icons/arcticons/hamburger-menu')['default']
    IconArcticonsImageCombiner: typeof import('~icons/arcticons/image-combiner')['default']
    IconArcticonsMultiAppUninstaller: typeof import('~icons/arcticons/multi-app-uninstaller')['default']
    IconArcticonsNoxcleaner: typeof import('~icons/arcticons/noxcleaner')['default']
    IconArcticonsRectangleHorizontal: typeof import('~icons/arcticons/rectangle-horizontal')['default']
    IconArcticonsSquare: typeof import('~icons/arcticons/square')['default']
    IconArcticonsWearInstaller: typeof import('~icons/arcticons/wear-installer')['default']
  }
}
